name: Issue Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - '*'

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set issue status based on commit or pull request
      run: |
        ISSUE_NUMBER=$(echo "$GITHUB_REF" | awk -F/ '{print $NF}')
        
        # Check if the issue is mentioned in a commit
        if git log --pretty=%B | grep -i "closes #$ISSUE_NUMBER" || git log --pretty=%B | grep -i "fixes #$ISSUE_NUMBER" || git log --pretty=%B | grep -i "#$ISSUE_NUMBER"; then
          echo "Issue mentioned in commit. Setting status to 'in Progress'."

          # Move the card to another column (replace PROJECT_ID and COLUMN_ID)
          curl -X POST \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/projects/3/moves \
            -d '{"position":"bottom","column_id":"4","card_id":"$ISSUE_NUMBER"}'
        fi
        
        # Check if the issue is linked to a pull request
        if gh pr view $ISSUE_NUMBER; then
          echo "Issue linked to pull request. Setting status to 'in Review'."

          # Move the card to another column (replace PROJECT_ID and COLUMN_ID)
          curl -X POST \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/projects/3/moves \
            -d '{"position":"bottom","column_id":"5","card_id":"$ISSUE_NUMBER"}'
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
